export const citiesByStates: {
  [state: string]: { value: string; accepted: boolean }[];
} = {
  Punjab: [
    { value: 'Amritsar', accepted: true },
    { value: 'Barnala', accepted: true },
    { value: 'Bathinda', accepted: true },
    { value: 'Fazilka', accepted: true },
    { value: 'Faridkot', accepted: true },
    { value: 'Fatehgarh Sahib', accepted: true },
    { value: 'Ferozepur', accepted: true },
    { value: 'Gurdaspur', accepted: true },
    { value: 'Hoshiarpur', accepted: true },
    { value: 'Jalandhar', accepted: true },
    { value: 'Kapurthala', accepted: true },
    { value: 'Ludhiana', accepted: true },
    { value: 'Mansa', accepted: true },
    { value: 'Moga', accepted: true },
    { value: 'Mohali', accepted: true },
    { value: 'Muktsar', accepted: true },
    { value: 'Pathankot', accepted: true },
    { value: 'Patiala', accepted: true },
    { value: 'Rupnagar', accepted: true },
    { value: 'Sangrur', accepted: true },
    { value: 'Shahid Bhagat Singh Nagar', accepted: true },
    { value: 'Tarn Taran', accepted: true },
    { value: 'Malerkotla', accepted: true },
    { value: 'Chandigarh', accepted: true }
  ],
  'Himachal Pradesh': [
    { value: 'Bilaspur', accepted: true },
    { value: 'Chamba', accepted: true },
    { value: 'Hamirpur', accepted: true },
    { value: 'Kangra', accepted: true },
    { value: 'Kinnaur', accepted: true },
    { value: 'Kullu', accepted: true },
    { value: 'Lahaul and Spiti', accepted: true },
    { value: 'Mandi', accepted: true },
    { value: 'Shimla', accepted: true },
    { value: 'Sirmaur', accepted: true },
    { value: 'Solan', accepted: true },
    { value: 'Una', accepted: true }
  ],
  Haryana: [
    { value: 'Ambala', accepted: true },
    { value: 'Bhiwani', accepted: true },
    { value: 'Faridabad', accepted: true },
    { value: 'Fatehabad', accepted: true },
    { value: 'Gurgaon', accepted: true },
    { value: 'Hisar', accepted: true },
    { value: 'Jhajjar', accepted: true },
    { value: 'Jind', accepted: true },
    { value: 'Kaithal', accepted: true },
    { value: 'Karnal', accepted: true },
    { value: 'Kurukshetra', accepted: true },
    { value: 'Mahendragarh', accepted: true },
    { value: 'Mewat', accepted: true },
    { value: 'Palwal', accepted: true },
    { value: 'Panchkula', accepted: true },
    { value: 'Panipat', accepted: true },
    { value: 'Rewari', accepted: true },
    { value: 'Rohtak', accepted: true },
    { value: 'Sirsa', accepted: true },
    { value: 'Sonipat', accepted: true },
    { value: 'Yamunanagar', accepted: true },
    { value: 'Charkhi Dadri', accepted: true },
    { value: 'Chandigarh', accepted: true }
  ]
};
