import { Prisma } from '@prisma/client';
const nowDate = new Date();

//for: ses_revamp_template (AQAS)
export const sesRevampTemplateData: Prisma.SesRevampTemplateCreateManyInput[] = [
    {
        id: 1,
        name: "SES",
        description: "Session Evaluation System",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: "1871"
    },
    {
        id: 2,
        name: "SIS",
        description: "Investigation Evaluation System",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: "1871"
    }
];

//for: ses_revamp_meta_data
export const sesRevampMetaDataData: Prisma.SesRevampMetaDataCreateManyInput[] = [
    {
        id: 1,
        category: "Overall Session Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "Unsatisfactory",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 2,
        category: "Overall Session Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "Emerging Lower End",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 3,
        category: "Overall Session Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "Emerging Higher End",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 4,
        category: "Overall Session Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "Proficient",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 5,
        category: "Overall Session Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "Outstanding",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 6,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Coaching Session",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 7,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Session Evaluation",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 8,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Follow up on Coaching Session",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 9,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Tutor request",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 10,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Based on outlier data points",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 11,
        category: "Reason for Evaluation",
        sub_category: "NA",
        value_name: "NA",
        value: "Based on IVT findings",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 12,
        category: "Feedback Attendance",
        sub_category: "NA",
        value_name: "NA",
        value: "Yes",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 13,
        category: "Feedback Attendance",
        sub_category: "NA",
        value_name: "NA",
        value: "No",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 14,
        category: "Feedback Attendance",
        sub_category: "NA",
        value_name: "NA",
        value: "Tutor Absent",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 15,
        category: "Feedback Attendance",
        sub_category: "NA",
        value_name: "NA",
        value: "Not required",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 16,
        category: "SR Completion",
        sub_category: "NA",
        value_name: "NA",
        value: "On or before deadline",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 17,
        category: "SR Completion",
        sub_category: "NA",
        value_name: "NA",
        value: "Late",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 18,
        category: "SR Completion",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 19,
        category: "SR Completion",
        sub_category: "NA",
        value_name: "NA",
        value: "Not received",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 20,
        category: "Previous focus area status",
        sub_category: "NA",
        value_name: "NA",
        value: "Secured",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 21,
        category: "Previous focus area status",
        sub_category: "NA",
        value_name: "NA",
        value: "In progress",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 22,
        category: "Previous focus area status",
        sub_category: "NA",
        value_name: "NA",
        value: "Not yet",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 23,
        category: "Previous focus area status",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 24,
        category: "Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "1",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 25,
        category: "Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "2",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 26,
        category: "Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "3",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 27,
        category: "Rating",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 28,
        category: "Pupil’s Progress",
        sub_category: "NA",
        value_name: "NA",
        value: "Tutor actions aided in progress",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 29,
        category: "Pupil’s Progress",
        sub_category: "NA",
        value_name: "NA",
        value: "Progress made through pupil’s initiative",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 30,
        category: "Pupil’s Progress",
        sub_category: "NA",
        value_name: "NA",
        value: "No progress made",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 31,
        category: "Pupil’s Progress",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 32,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "Language",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 33,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "Subject Knowledge",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 34,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "SCT Assessment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 35,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "SCT Interaction",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 36,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "Familiarity",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 37,
        category: "Criteria",
        sub_category: "Language",
        value_name: "NA",
        value: "Overall Language Skills",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 38,
        category: "Criteria",
        sub_category: "Subject Knowledge",
        value_name: "NA",
        value: "Mistakes and Misconceptions",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 39,
        category: "Criteria",
        sub_category: "Subject Knowledge",
        value_name: "NA",
        value: "Conceptual Explanations",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 40,
        category: "Criteria",
        sub_category: "SCT Assessment",
        value_name: "NA",
        value: "Pre-Assessment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 41,
        category: "Criteria",
        sub_category: "SCT Assessment",
        value_name: "NA",
        value: "Adaptation",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 42,
        category: "Criteria",
        sub_category: "SCT Assessment",
        value_name: "NA",
        value: "Post-Assessment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 43,
        category: "Criteria",
        sub_category: "SCT Interaction",
        value_name: "NA",
        value: "Engagement",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 44,
        category: "Criteria",
        sub_category: "SCT Interaction",
        value_name: "NA",
        value: "Praising for effort",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 45,
        category: "Criteria",
        sub_category: "SCT Interaction",
        value_name: "NA",
        value: "Professionalism",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 46,
        category: "Criteria",
        sub_category: "Familiarity",
        value_name: "NA",
        value: "Session flow",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 47,
        category: "Criteria",
        sub_category: "Familiarity",
        value_name: "NA",
        value: "Classroom Resources",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 48,
        category: "Criteria",
        sub_category: "Familiarity",
        value_name: "NA",
        value: "Session Ops",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 49,
        category: "Required Action",
        sub_category: "NA",
        value_name: "NA",
        value: "Fill in the Issue Register",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 50,
        category: "Required Action",
        sub_category: "NA",
        value_name: "NA",
        value: "No action required",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 51,
        category: "Required Action",
        sub_category: "NA",
        value_name: "NA",
        value: "Raise to Academic Coach",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 52,
        category: "Outcome of the Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "All good",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 53,
        category: "Outcome of the Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Insignificant Incident",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 54,
        category: "Outcome of the Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Minor incident",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 55,
        category: "Outcome of the Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Major incident",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 56,
        category: "Outcome of the Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Critical incident",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 57,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Negative pupil comment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 58,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "TSL Ticket",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 59,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Random investigation",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 60,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "RLO Investigation",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 61,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag investigation",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 62,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "QA Findings",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 63,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "CPD target (SE)",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 64,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Raised by tutor",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 65,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Overall tutor performance (TSP)",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 66,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Overall tutor performance (FFP)",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 67,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "NLH Sessions",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 68,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Misdiagnosed LOs",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 69,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "All good",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 70,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Background noise",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 71,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not adhering to the teacher comment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 72,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "IVT not required",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 73,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "Session Recording Issue",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 74,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "Audio Issue",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 75,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "Tutor Unavailable",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 76,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "User Mistake",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 77,
        category: "Abandon Reason",
        sub_category: "NA",
        value_name: "NA",
        value: "Other",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 78,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Inappropriate troubleshooting",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 79,
        category: "Pillar",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 80,
        category: "Criteria",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 81,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Teaching the wrong LO",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 82,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Starting from the wrong S2S",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 83,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not ending the session on time (early/ late)",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 84,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Failure to extend the session",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 85,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Teaching the LO for more than accepted numbers of time",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 86,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not following the session flow",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 87,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Using a different language",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 88,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Unacceptable terminology",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 89,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Inappropriate tone of voice",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 90,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Not responding on time",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 91,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Lack of engagement",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 92,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not maintaining the professionalism - Other",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 93,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Not following safeguarding protocols",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 94,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Inaccurate marking of tech issues",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 95,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Inaccurate internal notes",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 96,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Inaccurate S2S marking",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 97,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Inaccurate marking of the tick box",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 98,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Deleting the wrong LO",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 99,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Reporting - Forgetting to delete the LO",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 100,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag - Raising the wrong category",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 101,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag - Failure to raise the red flag",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 102,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag - Unnecessary red flag",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 103,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag - Empty red flag",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 104,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Red flag - Incomplete red flag",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 105,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Poor Session Quality - SK",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 106,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Poor Session Quality - Language",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 107,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Poor Session Quality - SCT Interaction",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 108,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Poor Session Quality - SCT Assessment",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 109,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "Poor Session Quality - Familiarity",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 110,
        category: "Concern",
        sub_category: "NA",
        value_name: "NA",
        value: "NA",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 111,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Audio/ Connectivity Issues",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 112,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "LO Suitability",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 113,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Student's ratings",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 114,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Session ending time",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1871,
        updated_at: nowDate.toISOString(),
        updated_by: 1871
    },
    {
        id: 115,
        category: "Point of Investigation",
        sub_category: "NA",
        value_name: "NA",
        value: "Student Engagement (PSFR)",
        status: "1",
        created_at: nowDate.toISOString(),
        created_by: 1870,
        updated_at: nowDate.toISOString(),
        updated_by: 1870
    }

];
