import { ApiProperty } from '@nestjs/swagger';

export class GetProgress200Dto {
  @ApiProperty({
    type: [],
    example: {
      personalDataEmp: 57,
      personalDataAuditor: 6,
      personalDataSidebarProg: 0,
      contactDataEmp: 29,
      contactDataAuditor: 2,
      contactDataSidebarProg: 0,
      educationDataEmp: 0,
      educationDataAuditor: 0,
      educationDataSidebarProg: 0,
      qualificationsDataEmp: 0,
      qualificationsDataAuditor: 0,
      qualificationsDataSidebarProg: 0,
      workExpEmp: 0,
      workExpAuditor: 0,
      workExpSidebarProg: 0,
      availabilityDataEmp: 0,
      availabilityDataAuditor: 0,
      availabilityDataSidebarProg: 0,
      itDataEmp: 0,
      itDataAuditor: 0,
      itDataSidebarProg: 0,
      bankDataEmp: 80,
      bankDataAuditor: 0,
      bankDataSidebarProg: 0,
      healthDataEmp: 0,
      healthDataAuditor: 0,
      healthDataSidebarProg: 0,
      right2workInfoEmp: 0,
      right2workInfoAuditor: 0,
      right2workInfoSidebarProg: 0,
      refereeDataEmp: 0,
      refereeDataAuditor: 0,
      refereeDataSidebarProg: 0,
      tutorStatus: 'initial audit fail',
      profileStatus: 'onboarding ready',
      initialAuditPassDate: '2023-06-01T00:00:00.000Z',
      contractAuditPassDate: null,
      finalAuditPassDate: null,
      dbsAuditPassDate: null,
      personalDataCount: '8/14',
      contactDataCount: '5/17',
      educationalDataCount: null,
      qualificationDataCount: null,
      workExperienceDataCount: null,
      bankDataCount: '4/5',
      refereeDataCount: null,
      healthDataCount: null,
      itDataCount: null,
      availabilityDataCount: null
    }
  })
  data: any[];
}
